"use client";

import Image from "next/image";
import { useCallback, useEffect, useId, useMemo, useState } from "react";
import { InfoTip } from "@/components/ui/InfoTip";
import { CLOAK_PAY } from "@/lib/site-links";
import { CloakPayPageHeader } from "./CloakPayPageHeader";

function useOrigin() {
  const [origin, setOrigin] = useState("");
  useEffect(() => {
    if (typeof window === "undefined") return;
    setOrigin(window.location.origin);
  }, []);
  return origin;
}

export function CloakPayPresentPage() {
  const origin = useOrigin();
  const [businessLabel, setBusinessLabel] = useState("Demo counter");
  const [amount, setAmount] = useState("");
  const [copyFlash, setCopyFlash] = useState(false);
  const baseId = useId();

  const payUrl = useMemo(() => {
    if (!origin) return "";
    const u = new URL(`${CLOAK_PAY.path}/pay`, origin);
    u.searchParams.set("source", "qr");
    u.searchParams.set("label", businessLabel.slice(0, 80) || "Business");
    const a = amount.trim();
    if (a) u.searchParams.set("amount", a);
    return u.toString();
  }, [origin, businessLabel, amount]);

  const qrImageSrc = useMemo(() => {
    if (!payUrl) return "";
    return `https://api.qrserver.com/v1/create-qr-code/?size=220x220&margin=8&data=${encodeURIComponent(payUrl)}`;
  }, [payUrl]);

  const onCopy = useCallback(async () => {
    if (!payUrl) return;
    try {
      await navigator.clipboard.writeText(payUrl);
      setCopyFlash(true);
      setTimeout(() => setCopyFlash(false), 2000);
    } catch {
      setCopyFlash(false);
    }
  }, [payUrl]);

  return (
    <div className="mx-auto max-w-3xl px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
      <CloakPayPageHeader
        kicker="Present at the counter"
        title="Pay link & QR"
        description="Encode the customer view URL with a label and optional amount. The QR points to the Customer pay page in this app (prototype)."
      />

      <section
        id="section-present-qr"
        className="app-card mb-6 scroll-mt-24 border-emerald-200/30 bg-gradient-to-b from-white to-emerald-50/15"
      >
        <h2 className="flex items-center gap-1 text-sm font-semibold text-slate-900">
          Build the link
          <InfoTip text="The QR is generated by a public API; ship with a local or npm QR renderer in production. Query params are illustrative." />
        </h2>
        <div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-start">
          <div className="min-w-0 flex-1 space-y-3">
            <div>
              <label className="app-label" htmlFor={`${baseId}-label`}>
                Business / location label
              </label>
              <input
                id={`${baseId}-label`}
                className="app-input"
                value={businessLabel}
                onChange={(e) => setBusinessLabel(e.target.value)}
                autoComplete="off"
              />
            </div>
            <div>
              <label className="app-label" htmlFor={`${baseId}-amount`}>
                Suggested amount (USDC, optional)
              </label>
              <input
                id={`${baseId}-amount`}
                className="app-input"
                value={amount}
                onChange={(e) => setAmount(e.target.value)}
                inputMode="decimal"
                placeholder="e.g. 12.00"
                autoComplete="off"
              />
            </div>
          </div>

          <div className="mx-auto flex shrink-0 flex-col items-center sm:mx-0">
            {qrImageSrc && (
              <div className="rounded-2xl border border-slate-200/80 bg-white p-3 shadow-sm">
                <Image
                  src={qrImageSrc}
                  alt="QR code encoding the pay link"
                  width={220}
                  height={220}
                  className="h-auto w-[220px] max-w-full"
                  unoptimized
                />
              </div>
            )}
            {qrImageSrc && (
              <a
                href={payUrl}
                className="mt-2 break-all text-center text-[10px] text-slate-500 underline decoration-slate-300/80 underline-offset-1 hover:text-indigo-800"
              >
                Open as customer
              </a>
            )}
          </div>
        </div>

        {payUrl && (
          <div className="mt-5">
            <p className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">Pay URL</p>
            <p className="mt-1 break-all rounded-lg border border-slate-200/60 bg-slate-50/80 px-3 py-2 font-mono text-xs text-slate-800">
              {payUrl}
            </p>
            <div className="mt-2 flex flex-wrap gap-2">
              <button type="button" className="btn-primary" onClick={() => void onCopy()}>
                {copyFlash ? "Copied" : "Copy pay link"}
              </button>
            </div>
          </div>
        )}
      </section>

      <section id="section-present-print" className="app-card scroll-mt-24 border-slate-200/80">
        <h2 className="text-sm font-semibold text-slate-900">Print</h2>
        <p className="mt-1 text-sm text-slate-600">
          A production build would add a <strong>print CSS</strong> view (logo, QR, amount, and policy) for reception desks.
        </p>
        <button
          type="button"
          className="btn-secondary mt-3"
          onClick={() => (typeof window !== "undefined" ? window.print() : void 0)}
        >
          Print this page
        </button>
      </section>
    </div>
  );
}
